# Generated by Django 5.2.3 on 2025-07-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_carad_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carad',
            options={'permissions': [('can_edit_all_ads', 'Can edit all ads')]},
        ),
    ]
