# Generated by Django 5.2.3 on 2025-07-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_carad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carad',
            options={'permissions': [('can_edit_all_ads', 'Can edit all ads'), ('can_delete_any_ad', 'Can delete any car ad')]},
        ),
    ]
